### ISSUE TITLE
Substituir ícone da lista de discussão

### ISSUE THREAD

**Issue by barrosgg** [womozbrasil/dev-site#10]
Remover ícone da **Lista de Discussão** do rodapé

**Comment by cyz** [comment]
Geraldo,
A Ioana está movimentando o bug do Discourse. Acho que finalmente teremos nossa category, podemos substituir o link da lista, pelo discourse. O que acha?

**Comment by barrosgg** [comment]
É perfeito.

**Comment by barrosgg** [comment]
![9d543e92b15b06924249654667a81441a55867eb](https://cloud.githubusercontent.com/assets/14970832/12735674/afd35a8c-c930-11e5-8cd2-43e856214cee.png)

**Comment by theus** [comment]
Esse ícone vai entrar no footer no lugar do _Lista de Discussão_ ou vai ser acrescentado?

**Comment by barrosgg** [comment]
A ideia da Cynthia é substituir o link apenas do link da lista de email para o link da categoria do Discourse.

**Comment by theus** [comment]
Eu não tinha visto o primeiro comentário. Mas então vai substituir no footer também, certo?

**Comment by barrosgg** [comment]
@theus eu to achando que vai ficar mais legal se por o ícone do Discourse no lugar do ícone da lista de email, o que acha?
Vai substituir em todo e qualquer lugar que tenha algo sobre a lista de email, pois a mesma não será mais utilizada pela nossa #teamwork hahaha...

**Comment by theus** [comment]
Também acho que ficará mais legal :relieved:

**Comment by barrosgg** [comment]
O que acha @cynthiapereira e @cyz ?

**Comment by theus** [comment]
Inclusive, essa alteração é feita no próprio tema

![image](https://cloud.githubusercontent.com/assets/61322/13029031/11271db4-d25f-11e5-8ce6-f31a634ca2b9.png)

[[ícone]](https://www.discourse.org/images/icon.png)

**Comment by cpswsg** [comment]
A minha intenção era essa, substituir o ícone pelo do discourse.
Podem fazer... =)

**Comment by cyz** [comment]
Exatamente isso, é para remover o link da lista de e-mails e adicionar o discourse. Ainda não temos a categoria, mas temporariamente, podemos linkar para: https://discourse.mozilla-community.org/t/womoz-brasil-topico-oficial/1647

**Comment by theus** [comment]
Então, essa alteração é feita pelo painel do Wordpress =)

**Comment by barrosgg** [comment]
@theus, ficou um máximo! Assim que enviar as alterações, não se esqueça de comentar aqui que a solicitação foi atendida, link para o Mozillians e feche a issue.

**Comment by theus** [comment]
@barrostecnologia essa alteração do ícone pode ser diretamente no código mas o tema do WozMoz permite a substituição através do próprio Wordpress, através do _Aparência > Personalizar_. Então é melhor fazer direto no painel, não? Lá dá para alterar o ícone, o nome e o link.

[[ícone]](https://www.discourse.org/images/icon.png)

**Comment by barrosgg** [comment]
Eu acredito que o ideal é fazer a alteração direto no código e assim fazer o controle de versionamento aqui no GiHub.
@cynthiapereira  @cyz

**Comment by cpswsg** [comment]
Isso mesmo @theus, diretamente no painel!

@barrostecnologia Faremos no painel pois, quando precisarmos alterar a o link novamente com a nossa categoria do discourse, qualquer pessoa com as permissões de alterar o tema, poderá fazer.

**Comment by cpswsg** [comment]
Done!
