### ISSUE TITLE
Criar metabox para os icones da area de Projetos

### ISSUE THREAD

**Issue by cyz** [womozbrasil/dev-site#16]

**Comment by theus** [comment]
Como seriam esses ícones? Seria tipo assim?
![image](https://cloud.githubusercontent.com/assets/61322/13050964/6a709450-d3d5-11e5-91c2-ff1b38ec6c31.png)

**Comment by cyz** [comment]
@theus vamos tentar usar ícones do font awesome. vou ver alguns ícones e já colo aqui as referências par adicionar lá

**Comment by theus** [comment]
Eu usei do font awesome o/

**Comment by cyz** [comment]
Não tinha visto os ícones haha
No caso, vamos estabelecer padrão para 'educação', 'eventos' e 'desenvolvimento'

**Comment by theus** [comment]
Certo. Cada ícone é adicionado através de um campo na edição do post, onde esse campo recebe o código do ícone do font awesome. E só vale para Projetos? Os ícones aparecem na listagem de projetos e na página individual também?

**Comment by cyz** [comment]
educação: fa-heart
dev: fa-github-alt
eventos: fa-camera-retro

**Comment by cyz** [comment]
Pode ser adicionado um select da categoria, para evitar erros na inclusão do projeto. Vale somente para projetos e o ícone aparece só na home, na página do projeto podemos usar igual ao modelo de post (conteúdo livre)

**Comment by halcance** [comment]
Issue fechado e passado para o https://github.com/womozbrasil/dev-site/issues/24 para andamento do processo.
