### ISSUE TITLE
Montar Wiki com passo-a-passo do GIT

### ISSUE THREAD

**Issue by FabioBeneditto** [womozbrasil/dev-site#23]
Ideias:
- [x] Configuração do GIT
- [x] Forks
- [x] Branches
- [x] Pull Requests

**Comment by halcance** [comment]
Criado **Configuração do GIT** mas só formatei algumas partes. Sintam-se à vontade para usar o markdown para formatação.

**Comment by halcance** [comment]
Pull request em português: https://git-scm.com/book/pt-br/v1/Git-Distribu%C3%ADdo-Contribuindo-Para-Um-Projeto

**Comment by halcance** [comment]
Pull request precisa de formatação e imagens.

Artigo da Wiki: https://github.com/womozbrasil/dev-site/wiki/5.2-Git-Distribu%C3%ADdo---Contribuindo-Para-Um-Projeto

Imagens diretamente do Github:
https://git-scm.com/book/pt-br/v1/Git-Distribu%C3%ADdo-Contribuindo-Para-Um-Projeto
